soc/api/urls.py
from django.urls import path

from .views import  api_detail_view_sp, APISPListView, sp_registration_view, add_review_sp, edit_review_sp,sp_detail_api

app_name = 'soc'

urlpatterns = [
    path('listsp',APISPListView.as_view(), name="listsp"),
    path('detailsp/<slug>/',api_detail_view_sp, name="detail"),
    path('registersp',sp_registration_view, name="register"),
    #for review section
	path('addreview/<slug>/',add_review_sp,name="addreview"),
    path('editreview/<slug>/<int:review_id>',edit_review_sp,name="editreview"),
    path('spreview/<slug>',sp_detail_api,name="review")

    #user id and timestamp encode
]

soc/urls.py
from django.urls import path
from rest_framework.urls import app_name

from . import views
from .views import (add_review, delete_review, detail_sp, edit_review,
                    home_view, list_sp, add_sp)

app_name = 'soc'

urlpatterns = [
    path('', home_view.as_view(), name='home'),
    path('serviceproviders/', views.list_sp, name='list'),
    path('serviceproviders/details/<slug>/', views.detail_sp, name='details'),
    path('serviceproviders/addreview/<slug>/', views.add_review, name='add_review'),
    path('addserviceprovider/', views.add_sp, name='add_sp'),

    path('serviceproviders/editreview/<slug>/<int:review_id>', views.edit_review, name='edit_review'),
    path('serviceproviders/deletereview/<slug>/<int:review_id>', views.delete_review, name='delete_review'),
    

]

test1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soc.urls')),
    path('account/', include('accounts.urls')),
    # path('', include('maps.urls')),
        #restframework
    path('api/soc/', include('soc.api.urls', 'soc_api')),
    path('api/account/', include('accounts.api.urls', 'accounts_api')),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token




class MyAccountManager(BaseUserManager):
        def create_user(self, email, username, fname, lname, contact_no, bike_no, password=None):
            if not email:
                raise ValueError("user must have an email address")
            if not username:
                raise ValueError("user must have username")
            if not fname:
                raise ValueError("user must have first name")
            if not lname:
                raise ValueError("user must have last name")
            if not contact_no:
                raise ValueError("user must have contact no")
            if not bike_no:
                raise ValueError("user must have bike no")

            user = self.model(
                    email       = self.normalize_email(email),
                    username    = username,
                    fname       = fname,
                    lname       = lname,
                    contact_no  = contact_no,
                    bike_no     = bike_no,
            )
            user.set_password(password)
            # user.self._db(password)
            user.save(using=self._db)
            return user

        def create_superuser(self, email, username, fname, lname, contact_no, bike_no, password):
            user = self.create_user(
                email       = self.normalize_email(email),
                password    = password,
                username    = username,
                fname       = fname,
                lname       = lname,
                contact_no  = contact_no,
                bike_no     = bike_no,
            )
            user.is_admin       = True
            user.is_staff       = True
            user.is_superuser   = True
            user.save(using=self._db)
            return user


class Account(AbstractBaseUser):
    email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
    #must include field
    username 				= models.CharField(max_length=30, unique=True)
    date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin				= models.BooleanField(default=False)
    is_active				= models.BooleanField(default=True)
    is_staff				= models.BooleanField(default=False)
    is_superuser			= models.BooleanField(default=False)
    #added later
    fname                   = models.CharField(max_length=30)
    lname                   = models.CharField(max_length=30)
    contact_no              = models.CharField(max_length = 10 , unique=True)
    bike_no                 = models.CharField(max_length=50, unique=True)

    USERNAME_FIELD          = 'email'
    REQUIRED_FIELDS         = ['username', 'fname', 'lname', 'contact_no', 'bike_no']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self , app_label):
        return True

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

soc/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
# from django.utils.text import slugify
from django.template.defaultfilters import slugify
import base64






# def upload_location(instance, filename):
#i can make it more usable by allowing user to upload multiple photos, contact no,

class Service_Provider(models.Model):
	name            =  models.CharField(max_length=100)
	panno           =  models.CharField(max_length=30, unique=True,blank=True, null=False)
	about           =  models.TextField(max_length=50)
	location        =  models.CharField(max_length=100)
	contactno       =  models.CharField(max_length=10,unique=True)
	averageRating   =  models.FloatField(default=0)#need to remove
	image           =  models.ImageField(upload_to='sp_pics')
	is_approved		=  models.BooleanField(default=False)
	date_joined		= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	date_updated 	= models.DateTimeField(auto_now=True, verbose_name="date updated")
	Posted_by		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)		
	slug			= models.SlugField(unique=True, editable=False)


# fields = ('name', 'panno', 'location', 'about', 'image', 'contactno')

	#https://www.youtube.com/watch?v=lSX8nzu9ozg&list=PLeyK9Dw9ShReHUdt5Nh2qlgF6keN6DI7z&index=32
 
 #multiple photos
 #https://stackoverflow.com/questions/34006994/how-to-upload-multiple-images-to-a-blog-post-in-django

	def __str__(self):
		return self.name


	class Meta:
		verbose_name 		= 'Service Provider'
		verbose_name_plural = 'Service Provider'
	# def save(self,*args,**kwargs):
	# 	super(Service_Provider,self).save(*args,**kwargs)
	# 	if not self.slug:
	# 		self.slug = slugify(self.name+'-'+str(self.id))
	# 		super(Service_Provider,self).save(*args,**kwargs)
 #wecanencode the field
	def save(self,*args,**kwargs):
		if not self.slug:
			#this is used to check the ValueError
			# breakpoint()
			self.slug = slugify(self.name+'-'+self.panno)
		super(Service_Provider,self).save(*args,**kwargs)
 
	# @property
	# def review(self):
	# 	return self.review_set.all()

# #it helps to check the pre existing foelds or not
# def pre_save_sp(sender, instance, *args, **kwargs):
# 	if not instance.slug:
# 		instance.slug = slugify(instance.name + "-" +  str(instance.object.id))
  
# pre_save.connect(pre_save_sp, sender=Service_Provider)


class Review(models.Model):
	service_provider = models.ForeignKey(Service_Provider, on_delete=models.CASCADE)
	user 			 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="reviews")
	comment  		 = models.TextField(max_length=800)
	rating 			 = models.FloatField(default=0)
	timestamp		 = models.DateTimeField(auto_now_add=True)
	#integer field can be consider for best use

	def __str__(self):
		return self.user.username

	def is_allowed(self, user):
		return self.user == user

	@property
	def user_name(self):
	 	return self.user.username
class about_member(models.Model):
	name		= models.CharField(max_length=30)
	expertise 	= models.TextField(max_length=15)
	fb_link 	= models.CharField(max_length=100)
	tw_link 	= models.CharField(max_length=100)
	lk_link 	= models.CharField(max_length=100)
	image 		= models.ImageField(upload_to='member_pics')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name 		= 'About Member'
		verbose_name_plural = 'About Member'

class home_page(models.Model):
	slider_image 	= models.ImageField(upload_to='slider_pics')
	sliding_text	= models.TextField(max_length=30)

	def __str__(self):
		return self.sliding_text

	class Meta:
		verbose_name 		= 'Home Page'
		verbose_name_plural = 'Home Page'

soc/forms.py
from django import forms
from .models import  (
    Service_Provider,
    Review,
)

#add sp form

class  SPForm(forms.ModelForm):
    class Meta():
        model = Service_Provider
        fields = ('name', 'panno', 'location', 'about', 'image', 'contactno')
        
class ReviewForm(forms.ModelForm):
    class Meta():
         model = Review 
         fields = ('comment', 'rating')

soc/api/views.py
from rest_framework import status
from rest_framework.decorators import api_view,permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import  ListAPIView
from .serializers import (
	Service_ProviderCreateSerializer,
	ServiceProviderListSerializer,
	Service_PSerializer,
	Review_SPSerializer,
 	ReviewSP_Detail,
	ServiceProviderUpdateSerializer,
)
from soc.models import Service_Provider, Review
from rest_framework.authentication import TokenAuthentication
from rest_framework import  serializers
from soc.models import Service_Provider
from rest_framework.filters import  SearchFilter, OrderingFilter

#https://medium.com/@syarif.secondchance/vs-code-python-unresolved-import-warning-ea9bba3fa9af

@api_view(['POST'])
@permission_classes((IsAuthenticated,))
def sp_registration_view(request):
	if request.method == 'POST':
		data = request.data
		data['Posted_by'] = request.user.pk
		serializer = Service_ProviderCreateSerializer(data=data)
		data = {}

		if serializer.is_valid():
			service_provider = serializer.save()
			data['response'] = "Successfully Registered"
			data['pk'] = service_provider.pk
			data['slug'] = service_provider.slug
			data['name'] = service_provider.name
			data['panno'] = service_provider.panno
			data['location'] = service_provider.location
			data['about'] = service_provider.about
			data['contactno'] = service_provider.contactno
			data['username'] = service_provider.Posted_by.username
			data['date_updated'] = service_provider.date_updated
			image_url = str(request.build_absolute_uri(service_provider.image.url))
			if "?" in image_url:
				image_url = image_url[:image_url.rfind("?")]
			data['image'] = image_url
			return Response(data=data)
	return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

		
@api_view(['GET', ])
@permission_classes((IsAuthenticated,))
def api_detail_view_sp(request, slug):
	try:
		service_provider = Service_Provider.objects.get(slug=slug)
	except Service_Provider.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)
	if request.method == 'GET':
		serializer = ServiceProviderListSerializer(service_provider)
		return Response(serializer.data)

@api_view(['PUT', ])
def api_update_sp(request, slug):
	try:
		service_provider = Service_Provider.objects.get(slug=slug)
	except Service_Provider.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)
	
	if request.method== "PUT":
		serializer = ServiceProviderUpdateSerializer(service_provider, data=request.data, partial=True)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data["success"]  = "updated"            
			data["name"]    = service_provider.name
			data["panno"]    = service_provider.panno
			data["contact_no"]    = service_provider.contact_no
			data["date_updated"]    = service_provider.date_updated
			
			image_url = str(request.build_absolute_uri(service_provider.image.url))
			if "?" in image_url:
				image_url = image_url[:image_url.rfind("?")]
				return Response(data=data)
		return Response(serializer.data, status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE', ])
def api_delete_sp(request, slug):
	try:
		service_provider = Service_Provider.objects.get(slug=slug)
	except Service_Provider.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)
	
	if request.method== "DELETE":
		serializer = Service_PSerializer(service_provider)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data["sucess"] = "updated"
			return Response(data=data)
		return Response(serializer.data, status=status.HTTP_400_BAD_REQUEST)

class APISPListView(ListAPIView):
	queryset                = Service_Provider.objects.all()
	serializer_class        = ServiceProviderListSerializer
	authentication_classes  = (TokenAuthentication,)
	permission_classes      = (IsAuthenticated,)
	pagination_class        = PageNumberPagination
	
	filter_backends         = (SearchFilter,OrderingFilter)
	search_fields           = ('name', 'panno', 'location')
	
class APISP_DetailView():
	serializer_class = Service_PSerializer
	
	def get_queryset(self):
		queryset = Service_Provider.objects.all()
		return super().get_queryset()
	
	
@api_view(['POST', ])
@permission_classes((IsAuthenticated,))
def add_review_sp(request, slug):
	# service_provider = Service_Provider(slug=slug)
	if request.method == "POST":
		data 				= request.data.copy()
		data['user'] 	= request.user.pk
		data["service_provider"] = Service_Provider.objects.get(slug=slug).pk
		print(request.data)
		print(data)
		serializer 			= Review_SPSerializer(data=data)
		data = {}
		if serializer.is_valid():
			review_sp 			= serializer.save()
			data['response']	= 'Review Added Successfully'
			data['pk']			= review_sp.pk
			data['comment']		= review_sp.comment
			data['rating']		= review_sp.rating
			data['timestamp']	= review_sp.timestamp
			return Response(data=data)
		return Response(serializer.errors, status=400)
#for this part in front end we have to check for request.user.pk vs review.user.pk
@api_view(['POST',])
@permission_classes((IsAuthenticated,))
def edit_review_sp(request, slug, review_id):
	if request.method == "POST":
		data = request.data.copy()
		data['user'] 	= request.user.pk
		data["service_provider"] = Service_Provider.objects.get(slug=slug).pk
		review = Review.objects.get(service_provider=data["service_provider"], id = review_id)
		# if request.user == review.user :
		if review.is_allowed(request.user):
			print(request.POST)
			print(data)
			serializer =  Review_SPSerializer(data=data)
			if serializer.is_valid():
				review_sp = serializer.save()
				data['response'] : 'Review Updated Successfully'
				data['pk'] : review_sp.pk
				data['comment'] : review_sp.comment
				data['rating']		= review_sp.rating
				data['timestamp']	= review_sp.timestamp
				return Response(data=data)
		return Response(data={'response':'Not allowed'},status=status.HTTP_405_METHOD_NOT_ALLOWED)


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def sp_detail_api(request, slug):
	try:
		service_provider = Service_Provider.objects.get(slug=slug)
	except Service_Provider.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	reviews = Review.objects.filter(service_provider=service_provider)
	serializer = ReviewSP_Detail(reviews,many=True)
	return Response(serializer.data)
	























# class ReviewServiceProviderViewSet(viewsets.ModelViewSet):
#     serializer_class = Review_SPSerializer
	
#     def get_queryset(self):
#         return Review.objects.filter(
#             service_provider__slug=self.request.slug
#         )
		
#     def create(self, request, pk=None):
#             service_provider = Service_Provider.objects.get(id=service_provider_slug)
#             serializer = Review_SPSerializer(data=request.data)
#             if serializer.is_valid():
#                 serializer.save(service_provider=service_provider)
#                 return Response(serializer.data)
#             else:
#                 return Response(serializer.errors,
#                                 status=status.HTTP_400_BAD_REQUEST)

#         def retrieve(self, request, pk=None):
#             service_provider = Service_Provider.objects.get(pk=pk)
#             serializer = PasswordSerializer(contact.contactphonenumber_set.all(), many=True)
#             return Response(serializer.data)
	# @action(methods=['post'], detail=False)
	# def add_review_to_sp(self, request, id=service_provider_id):
	#     service_provider    = Service_Provider.objects.get(id=service_provider_id)
	#     serializer          = Review_SPSerializer(data=request.data)
	#     if serializer.is_valid():
	#         serializer.save(service_provider=service_provider)
	#         return Response(serializer.data)
	#     else:
	#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
		
	# @action(methods=['get'], detail=False)
	

templates/soc/add_sp.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
	<div class="login-page signup">
		<div class="container">
			<div class="d-flex justify-content-center h-100">
				<div class="card">
			    <form method="POST" enctype="multipart/form-data" action="{% url 'soc:add_sp' %}" >
                            {% csrf_token %}
                            <br>
                            <br>
                            <br>
                            <br>
							<div class="form-group">
                    <input type="text" name="name" class="form-control" id="name" autocomplete="off" placeholder="Service Provider Name">
                    <span id="id_fname" class="text-danger font-weight-bold"> </span>
                </div>
                <div class="form-group">
                    <input type="text" name="panno" class="form-control" id="panno" autocomplete="off" placeholder="Pan No.">
                    <span id="id_lname" class="text-danger font-weight-bold"> </span>
                </div>

                <div class="form-group">
                    <input type="text" name="about" class="form-control" id="user" autocomplete="off" placeholder="About Service Provider">
                    <span id="about" class="text-danger font-weight-bold"> </span>
                </div>

                <div class="form-group">
                    <input type="text" name="contactno" class="form-control" id="contactno" autocomplete="off" placeholder="Contact  Number">
                    <span id="contact_no" class="text-danger font-weight-bold"> </span>
                </div>
                <div class="form-group">
                    <input type="text" name="location" class="form-control" id="location" autocomplete="off" placeholder="Location">
                    <span id="contact_no" class="text-danger font-weight-bold"> </span>

                </div>

                <div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*"  required>
				</div>

							<div class="form-group">
								<input type="submit" value="Add SP" class="btn float-right login_btn">
                            </div>
                            <br>
                            <br>

                            <br>
                            <br><br>
                            <br>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
  


{% endblock content %}

templates/soc/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="breadcrumbs overlay" data-stellar-background-ratio="0.7">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul class="list">
                    <li><a href="">Home</a></li>
                    <li><a href="#">{{ sp.name }}</a></li>
                </ul>
                <h2>{{ sp.name }}</h2>
            </div>
        </div>
    </div>
</div>
<!--/ End Breadcrumb -->

<div class="service-single-first-section section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="sec-title">
                    <h1>{{ sp.name }}</h1>
                </div>
                <div class="text">
                    <p>{{sp.about}}</p>
                    <div class="info-agents color-a">
                      <p>
                        <strong>Pan Number: </strong>
                        <span class="color-text-a">{{sp.panno}}</span>
                      </p>
                      <p>
                        <strong>Mobile: </strong>
                        <span class="color-text-a"> {{sp.contactno}}</span>
                      </p>
                      <p>
                        <strong>Email: </strong>
                        <span class="color-text-a"> agents@example.com</span>
                      </p>
                      <p>
                        <strong>Address:</strong>
                        <span class="color-text-a">{{sp.location}}</span>
                      </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="merchant-image">
                    <img src='/media/{{sp.image}}' alt="images">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="feature-section merchant-features">
    <div class="container">
        <div class="merchant-features-title">
            <div class="merchant-features-title text-center">
                <h3>Merchant<span>&nbsp;Feature</span></h3>
            </div>
        </div>
        <div class="main-feature-body">
            <div class="row no-gutters">
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="featured-content">
                        <div class="featured-content-main feature-style-1 ">
                            <div class="feature-icon">
                                <div class="feature-icon-body">
                                    <i class="far fa-check-square"></i>
                                </div>
                            </div>
                            <h2 class="medium-font">
                                    Financial Planning                               
                            </h2>
                            <div class="feature-process-desc">
                            <p>A digital agency isn't here to replace your internal team, we're here to partner with you and supplement your efforts.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="featured-content">
                        <div class="featured-content-main feature-style-2 ">
                            <div class="feature-icon">
                                <div class="feature-icon-body">
                                    <i class="far fa-check-square"></i>
                                </div>
                            </div>
                            <h2 class="medium-font">
                                    Retirement Planning                                
                            </h2>
                            <div class="feature-process-desc">
                            <p>A digital agency isn't here to replace your internal team, we're here to partner with you and supplement your efforts.</p>
                            </div>
                        </div>
                    </div>
                </div>
                

                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="featured-content">
                        <div class="featured-content-main feature-style-3 ">
                            <div class="feature-icon">
                                <div class="feature-icon-body">
                                    <i class="far fa-check-square"></i>
                                </div>
                            </div>
                            <h2 class="medium-font">
                                    Risk Management                               
                            </h2>
                            <div class="feature-process-desc">
                            <p>A digital agency isn't here to replace your internal team, we're here to partner with you and supplement your efforts.</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="featured-content">
                        <div class="featured-content-main feature-style-3 ">
                            <div class="feature-icon">
                                <div class="feature-icon-body">
                                    <i class="far fa-check-square"></i>
                                </div>
                            </div>
                            <h2 class="medium-font">
                                    Best services                                
                            </h2>
                            <div class="feature-process-desc">
                            <p>A digital agency isn't here to replace your internal team, we're here to partner with you and supplement your efforts.</p>
                            </div>
                        </div>
                    </div>
                </div>
                 
            </div>
        </div>
    </div>
</div>

<div class="merchant-review-section section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="merchant-review-title">
                    <h3>Reviews</h3>
                {% for review in reviews %}

                    <div class="media">
                      <img src={% static  "images/logo.png" %} class="mr-3" alt="...">
                      {% if request.user == review.user %}
                        <div class="edit-delete">
                            <a href="{% url 'soc:edit_review' sp.slug review.id   %}">Edit</a>
                            <a href="{% url 'soc:delete_review' sp.slug review.id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                        </div>
                      {% endif %}
                      <div class="media-body">
                        <h5 class="mt-0">{{ review.user.username }}</h5>
                        {{ review.comment }}
                      </div>
                    </div>
                {% endfor %}
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="contact-right-section">
                    <div class="contact-form-section">
                        <div class="contact-title">
                            Leave your Comments                            
                        </div>
                        <h5></h5>
                        <div class="form-section">
                            <!-- form section start here -->
                            <form action='{% url 'soc:add_review' sp.slug %}' method="POST">
                                {% csrf_token %}
                                <textarea name="comment" class="form-control" id="comment" cols="30" rows="10" placeholder="Review"></textarea>
                                <input type="text" class="form-control" id="rating" placeholder="Rate" name="rating">
                                
                                <br>
                                
                                {% if user.is_authenticated %}
                                <button class=" git-btn mt-30" type="submit">Submit</button>
                                {% else %}
                                    <h4>You need to be authenticated to comment </h4>
                                    <a href="{% url 'login' %}">Login</a>
                                {% endif %}
                                    
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    













{% endblock content %}

templates/soc/list_sp.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="breadcrumbs overlay" data-stellar-background-ratio="0.7">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul class="list">
                    <li><a href= "{% url 'soc:home'  %}" >Home</a></li>
                    <li><a href="#">Service Provider</a></li>
                </ul>
                <h2>Service Provider</h2>
            </div>
        </div>
    </div>
</div>
<!--/ End Breadcrumb -->

<!-- service section  -->
<div class="service-section section">
    <div class="container">
        <div class="section-title text-center">
            <h3><span>&nbsp;service Center</span></h3>
        </div>
        <div class="row">
        {% for service_provider in sp  %}
              
            <div class="col-md-4">
                <div class="service-section-wrap">
                    <div class="service-left service-all-details">
                        <div class="service-logo">
                            <img src="/media/{{service_provider.image}}">
                        </div>
                        <div class="service-logo-about">
                            <p>{{ service_provider.about }}</p>
                        </div>
                    </div>
                    <div class="service-right service-all-details">
                        <div class="service-tilte-name">
                            <h3>{{service_provider.name}}</h3>
                        </div>
                        <ul class="services-list">
                            <li><i class="fas fa-pen-nib"></i>{{service_provider.panno}}</li>
                            <li><i class="fas fa-map-marker-alt"></i>{{service_provider.location}}</li>
                            <li><i class="fas fa-phone"></i>{{service_provider.contactno}}</li>
                        </ul>
                        <div class="service-last service-rating">
                            <ul class="service-rating">
                                <li><i class="fas fa-star"></i></li>
                            </ul>
                        </div>
                    </div>
                    <a href="{% url 'soc:details' service_provider.slug %}">Details</a>
                </div>
            </div>
        {% endfor %}

        </div>
    </div>
</div>



{% endblock content %}